#!/usr/bin/env bash
# This script displays information about a subdomain
# It accepts 2 arguments - domain & subdomain

#subdomains=( "www" "lb-01" "web-01" "web-02" )

#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_lookup () {
    det=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $det" | awk '{print "The subdomain "$1" is a "$2" record and points to " $3}'
}

if [ $# -eq 1 ]
then
  domain_lookup $1 www
  domain_lookup $1 lb-01
  domain_lookup $1 web-01
  domain_lookup $1 web-02
elif [ $# -eq 2 ]
then
  domain_lookup $1 $2
fi

